<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_kota_edit profile</name>
   <tag></tag>
   <elementGuidId>367e28c4-d7d0-49ce-b304-21f7bad5e947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='kota']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'kota' and (text() = 'Pilih kotaBandungBogorJemberKediriLumajangMalangPasuruanProbolinggoYogyakarta' or . = 'Pilih kotaBandungBogorJemberKediriLumajangMalangPasuruanProbolinggoYogyakarta')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kota</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ce0ab58-7b88-42ce-94c1-82d7657a15be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>99aded4d-4c25-4eaf-882b-380de1c1a0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kota</value>
      <webElementGuid>b5bd5cb1-b4eb-4234-ad40-e7cdadfd3631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih kotaBandungBogorJemberKediriLumajangMalangPasuruanProbolinggoYogyakarta</value>
      <webElementGuid>dc3bbe38-e5ed-402b-b997-4b34abd26a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kota&quot;)</value>
      <webElementGuid>920134f8-5f56-44f2-b3d2-dc28e057cdaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='kota']</value>
      <webElementGuid>19e95b66-0571-49b2-8cf8-3724bbfc1d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div[2]/select</value>
      <webElementGuid>2179a1b1-7039-4f79-9dd2-84cd4aef8709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota*'])[1]/following::select[1]</value>
      <webElementGuid>581aea76-99b7-4771-823b-f2971c52a9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama*'])[1]/following::select[1]</value>
      <webElementGuid>235534ea-045c-4a46-98e9-88e78538b29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat*'])[1]/preceding::select[1]</value>
      <webElementGuid>2598736f-7c00-4cfa-ba50-1a5e2226a031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.Handphone*'])[1]/preceding::select[1]</value>
      <webElementGuid>013ebaf4-ad0f-463a-9615-ec5a2afc15ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0820b45b-fce9-4ba2-b892-6056b9212c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'kota' and (text() = 'Pilih kotaBandungBogorJemberKediriLumajangMalangPasuruanProbolinggoYogyakarta' or . = 'Pilih kotaBandungBogorJemberKediriLumajangMalangPasuruanProbolinggoYogyakarta')]</value>
      <webElementGuid>7ec9b5ef-2aec-4418-b96c-c3645bd7c84a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
