<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama produk_edit produk</name>
   <tag></tag>
   <elementGuidId>e42b9fa1-a593-4a9a-b503-c1d0b9792bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nm_produk']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'type' and @id = 'nm_produk' and @placeholder = 'Nama Produk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nm_produk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>784f8459-e060-4f4d-a7d4-761e6526aec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>d9beb4df-d145-4ee8-92fa-93f34c859a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ce8a5350-66ad-402b-bdbe-3e71e9cd133e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nm_produk</value>
      <webElementGuid>882defdf-5670-4c6d-b143-21dd3156c12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Produk</value>
      <webElementGuid>9103e735-9120-479e-9645-686bc65ec352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Meja</value>
      <webElementGuid>7e51140c-4de3-4fa1-8051-95628f5da9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nm_produk&quot;)</value>
      <webElementGuid>a13d6c87-38b2-428c-81de-fc7ddd95603d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nm_produk']</value>
      <webElementGuid>53d1b75b-698d-4d3a-97da-ab920ecc1f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/input</value>
      <webElementGuid>04e6359b-6f9d-45b8-bc53-06eb9552c6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>face575b-b757-4a13-b660-9afa36991b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'type' and @id = 'nm_produk' and @placeholder = 'Nama Produk']</value>
      <webElementGuid>25a6489e-ed92-4114-8e7d-5102885c86c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
