<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_harga buyer_notif1</name>
   <tag></tag>
   <elementGuidId>e5fa0381-e928-4c4d-a87b-d166318e3925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarText']/ul/li[2]/div/div/div[16]/div/div[2]/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d1cd729-4053-42f8-940d-24eb29ca6261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>2bd73678-5b1e-4234-8dce-8d43aec01fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ditawar Rp 10.000,00</value>
      <webElementGuid>4ec07a4d-8a64-43b5-b1a8-7324583cfef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarText&quot;)/ul[@class=&quot;navbar-nav me-auto mb-2 mb-lg-0&quot;]/li[@class=&quot;dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right p-2 show&quot;]/div[@class=&quot;flex-column row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;flex-column row&quot;]/div[@class=&quot;col&quot;]</value>
      <webElementGuid>00fbae01-e24e-4c28-9a48-4970c8f66154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarText']/ul/li[2]/div/div/div[16]/div/div[2]/div/div[4]</value>
      <webElementGuid>936fac9d-5a47-48ef-9c95-8cfd80f1816d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 50.000,00'])[1]/following::div[1]</value>
      <webElementGuid>d3968d83-8043-461b-8ab9-b10185f51913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='daun dan bunga'])[1]/following::div[2]</value>
      <webElementGuid>468c3f9d-7d36-4f99-95f9-7dbcefca716e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penawaran Produk Diterima'])[4]/preceding::div[2]</value>
      <webElementGuid>12fe3e8c-5aae-4c7e-bb17-f8ff83c89781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='daun dan bunga'])[2]/preceding::div[6]</value>
      <webElementGuid>04358f99-2ebe-4807-909c-28ead87fc04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[2]/div/div[4]</value>
      <webElementGuid>6d87d09a-98ed-4e14-a2f9-f4bedb172fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ditawar Rp 10.000,00' or . = 'Ditawar Rp 10.000,00')]</value>
      <webElementGuid>504ad80f-0561-47e0-aed5-3c893f797510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
